### PR TITLE
Add add-on attachment namespace

### PR DESCRIPTION
**Pull request by ratoma**

### CODE REVIEW

**Comment by ratoma** [comment]
This is related to: [Issue #279](https://github.com/heroku/terraform-provider-heroku/issues/279)

**Comment by davidji99** [comment]
I need to merge in #276 before the acceptance tests on this PR can run properly. You can rebase this PR with `master` afterwards. Stay tuned.

PR looks good.

**Comment by davidji99** [comment]
Please rebase with `master` branch. #276 is merged in.

**Comment by ratoma** [comment]
Done, the branch is now rebased with master.

**Comment by davidji99** [comment]
Well this is a bit problematic. Our acceptance workflow on Github actions make use of repo secrets that (rightfully) aren't set when running on a forked branch. I'll go ahead and merge this in while we explore any possible alternatives solutions.

**Pull request merged**
